# Pandas 한번에 제대로 배우기



---

In [2]:
import numpy as np
import pandas as pd
pd.__version__ # 판다스 버전 확인

'1.1.5'

## Pandas 객체

### Series 객체

In [3]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0]) # Series 는 인덱스와 함께 값을 저장한다
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [4]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s[1]

0.25

In [7]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [8]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], index=['a','b','c','d','e']) # 인덱스 지정이 가능
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [9]:
s['c']

0.5

In [10]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [11]:
'b' in s

True

In [12]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0], index=[2,4,6,8,10]) 
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
s[4]

0.25

In [14]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [15]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [17]:
s.isin([0.25, 0.75]) # [] 안에 값이 s에 존재하는지 boolean 형태로 반환

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [18]:
pop_tuple ={'서울특별시': 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 1471040,
            '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [19]:
population['서울특별시']

9720846

In [20]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [21]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

   A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [22]:
pd.DataFrame(np.random.rand(5,5),
             columns = ['A', 'B', 'C', 'D', 'E'],
             index=[1,2,3,4,5])

          A         B         C         D         E
1  0.234939  0.848754  0.894653  0.322359  0.994244
2  0.223005  0.223980  0.760093  0.115781  0.566587
3  0.796709  0.323851  0.264978  0.739025  0.287001
4  0.879002  0.351359  0.295168  0.722581  0.933709
5  0.714724  0.731143  0.877414  0.102952  0.688714

In [23]:
male_tuple ={'서울특별시': 4732275,
              '부산광역시': 1668618,
              '인천광역시': 1476813,
              '대구광역시': 1198815,
              '대전광역시': 734441,
              '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [24]:
female_tuple ={'서울특별시': 4988571,
              '부산광역시': 1735805,
              '인천광역시': 1470404,
              '대구광역시': 1229139,
              '대전광역시': 736599,
              '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [25]:
korea_df = pd.DataFrame({'인구수': population, # Series
                         '남자인구수': male,  # Series  
                         '여자인구수': female}) # Series
korea_df

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [26]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [27]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [28]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [29]:
korea_df['서울특별시':'인천광역시']

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체

In [30]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [31]:
idx[1]

4

In [32]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [33]:
idx[-1:]

Int64Index([10], dtype='int64')

In [34]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [35]:
print(idx)
print(idx.size) # 5개의 값이 들어감
print(idx.shape) # 1차원 shape
print(idx.ndim) # 1차원이라서 1이 출력
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64

#### Index 연산

In [36]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2)) # 합집합
print(idx1.difference(idx2)) # 차집합
print(idx1 - idx2) # 차집합과는 다르게 같은 자리에 값끼리 빼줌
print(idx1.intersection(idx2)) # 교집합
print(idx1 & idx2) # 교집합
print(idx1.union(idx2)) # 중복을 뺀 합집합
print(idx1 | idx2) # 중복을 뺀 합집합
print(idx1.delete(0)) # 0번째 값 삭제
print(idx1.drop(8)) # () 안에 값을 삭제
print(idx1 ^ idx2) # 공통점을 뺀 나머지 > 여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 2, 4, 6], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')



---

## 인덱싱(Indexing)

In [37]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [38]:
s['b']

0.25

In [39]:
'b' in s

True

In [40]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [41]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [42]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [43]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [45]:
s[(s >0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [46]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [47]:
s = pd.Series(['a','b','c','d','e'],
              index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [48]:
s[1]

'a'

In [49]:
s[2:4]

5    c
7    d
dtype: object

In [50]:
s.iloc[1]

'b'

In [51]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [52]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [53]:
s.reindex(range(10), method='bfill') # method='bfill'> 빈 값을 전에 있는 값으로 채워요

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱

In [54]:
korea_df

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [55]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [57]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [58]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [59]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [60]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [61]:
korea_df.T # 기존의 행과 열이 바뀌어 출력

              서울특별시         부산광역시  ...         대전광역시         광주광역시
인구수    9.720846e+06  3.404423e+06  ...  1.471040e+06  1.455048e+06
남자인구수  4.732275e+06  1.668618e+06  ...  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  ...  7.365990e+05  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  ...  9.970703e+01  9.796895e+01

[4 rows x 6 columns]

In [62]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [63]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [64]:
korea_df.loc[:'인천광역시',:'남자인구수']

           인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [65]:
korea_df.loc[(korea_df.여자인구수 > 1000000)] # 여자인구수가 1000000 초과인 지역을 알려주세요

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [66]:
korea_df.loc[(korea_df.인구수 < 2000000)] # 인구수가 2000000 미만인 지역을 알려주세요

           인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [67]:
korea_df.loc[(korea_df.인구수 > 2500000)] # 인구수가 2500000 초과인 지역을 알려주세요

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.loc[korea_df.남여비율 > 100] # 남여비율 중 남자가 더 많은 곳을 알려주세요

           인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [69]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

           인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [70]:
korea_df.iloc[:3,:2]

           인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [71]:
korea_df

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [72]:
idx_tuples = [('서울특별시', 2010),('서울특별시', 2020),
              ('부산광역시', 2010),('부산광역시', 2020),
              ('인천광역시', 2010),('인천광역시', 2020),
              ('대구광역시', 2010),('대구광역시', 2020),
              ('대전광역시', 2010),('대전광역시', 2020),
              ('광주광역시', 2010),('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [73]:
pop_tuples = [10312545, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [74]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [75]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [76]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [77]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [78]:
korea_mdf = population.unstack() # 다중인덱싱으로 만든 시리즈를 데이터 프레임으로 만들어줌
korea_mdf

           2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [79]:
korea_mdf.stack() # 데이터프레임을 다중인덱싱으로

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [80]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [81]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples})
korea_mdf

                총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [82]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [83]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples})
korea_mdf

                총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [84]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [85]:
ratio.unstack()

             2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [86]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [87]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index=[['a','a','b','b','c','c'], [1,2,1,2,1,2]],
                  columns = ['c1','c2','c3'])
df

           c1        c2        c3
a 1  0.314908  0.307050  0.815845
  2  0.955935  0.328253  0.717199
b 1  0.247091  0.231446  0.867874
  2  0.990180  0.192304  0.179562
c 1  0.963411  0.059803  0.678809
  2  0.076705  0.028401  0.426016

In [88]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'], [1,2,1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2),('c',1),('c',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
 pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
pd.MultiIndex(levels=[['a','b','c'],[1,2]],
              codes=[[0,0,1,1,2,2],[0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [92]:
population.index.names = ['행정구역','년도']
population

행정구역   년도
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [93]:
idx = pd.MultiIndex.from_product([['a','b','c'],[1,2]],
                                 names=['name1','name2'])
cols = pd.MultiIndex.from_product([['c1','c2','c3'],[1,2]],
                                  names=['col_name1','col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3
col_name2       1     2     1     2     1     2
name1 name2
a     1      0.28 -0.25  0.24 -0.23  0.84  1.67
      2     -0.64 -0.72  0.23 -1.51  0.20 -0.07
b     1     -2.24  0.32  0.33 -2.19  2.00  0.48
      2     -1.72  0.24  0.63 -1.54 -0.35 -0.51
c     1      1.44 -0.54 -0.75  0.50 -0.71 -0.43
      2      1.98  2.37 -1.52 -1.05  2.22 -1.67

In [94]:
mdf['c2']

col_name2       1     2
name1 name2
a     1      0.24 -0.23
      2      0.23 -1.51
b     1      0.33 -2.19
      2      0.63 -1.54
c     1     -0.75  0.50
      2     -1.52 -1.05

#### 인덱싱 및 슬라이싱

In [95]:
population

행정구역   년도
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [96]:
population['인천광역시', 2010]

2758296

In [97]:
population[:,2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [98]:
population[population > 3000000]

행정구역   년도
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [99]:
population[['대구광역시','대전광역시']]

행정구역   년도
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [100]:
mdf

col_name1      c1          c2          c3
col_name2       1     2     1     2     1     2
name1 name2
a     1      0.28 -0.25  0.24 -0.23  0.84  1.67
      2     -0.64 -0.72  0.23 -1.51  0.20 -0.07
b     1     -2.24  0.32  0.33 -2.19  2.00  0.48
      2     -1.72  0.24  0.63 -1.54 -0.35 -0.51
c     1      1.44 -0.54 -0.75  0.50 -0.71 -0.43
      2      1.98  2.37 -1.52 -1.05  2.22 -1.67

In [101]:
mdf['c2',1]

name1  name2
a      1        0.24
       2        0.23
b      1        0.33
       2        0.63
c      1       -0.75
       2       -1.52
Name: (c2, 1), dtype: float64

In [102]:
mdf.iloc[:3, :4]

col_name1      c1          c2
col_name2       1     2     1     2
name1 name2
a     1      0.28 -0.25  0.24 -0.23
      2     -0.64 -0.72  0.23 -1.51
b     1     -2.24  0.32  0.33 -2.19

In [103]:
mdf.loc[:,('c2',1)]

name1  name2
a      1        0.24
       2        0.23
b      1        0.33
       2        0.63
c      1       -0.75
       2       -1.52
Name: (c2, 1), dtype: float64

In [104]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:,2], idx_slice[:,2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2
a     2     -0.72 -1.51 -0.07
b     2      0.24 -1.54 -0.51
c     2      2.37 -1.05 -1.67

#### 다중 인덱스 재정렬

In [106]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [107]:
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [109]:
korea_mdf = korea_mdf.sort_index() # sort_index()로 정렬해준 다음 슬라이싱이 가능함
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [110]:
korea_mdf['서울특별시':'인천광역시']

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [111]:
korea_mdf.unstack(level=0)

         총인구수                    ...       남여비율
행정구역    광주광역시    대구광역시    대전광역시  ...      부산광역시      서울특별시       인천광역시
년도                               ...
2010  1454636  2511676  1503664  ...  98.798155  98.269140  101.638668
2020  1455048  2427954  1471040  ...  96.129346  94.862336  100.435867

[2 rows x 24 columns]

In [112]:
korea_mdf.unstack(level=1)

           총인구수             남자인구수  ...    여자인구수        남여비율
년도         2010     2020     2010  ...     2020        2010        2020
행정구역                               ...
광주광역시   1454636  1455048   721780  ...   734988   98.488653   97.968946
대구광역시   2511676  2427954  1255245  ...  1229139   99.905606   97.532907
대전광역시   1503664  1471040   753648  ...   736599  100.484256   99.707032
부산광역시   2567910  3404423  1773170  ...  1735805   98.798155   96.129346
서울특별시  10312545  9720846  5111259  ...  4988571   98.269140   94.862336
인천광역시   2758296  2947217  1390356  ...  1470404  101.638668  100.435867

[6 rows x 8 columns]

In [114]:
korea_mdf.stack()

행정구역   년도
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
       2020  총인구수     3.404423e+06
             남자인구수    1.668618e+06
             여자인구수    1.735805e+06
             남여비율     9.612935e+01
서울특별시  2010  총인구수     1.031254e+07
             남자인구수    5.111259e+06
             여자인구수    5.201286e+06
             남여비율     9.826914e+01
       2020  총인구수     9.720846e+06
             남자인구수    4.732275e+06
             여자인구수    4.988571e+06
             남여비율     9.486234e+01
인천광역시  2010  총인구수     2.758296e+06
             남자인구수    1.390356e+06
             여자인구수    1.367940e+06
             남여비율     1.016387e+02
       2020  총인구수     2.947217e+06
             남자인구수    1.476813e+06
             여자인구수    1.470404e+06
             남여비율     1.004359e+02
dtype: float64

In [116]:
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [117]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

       행정구역      총인구수    남자인구수    여자인구수        남여비율
년도
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [118]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

     행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [119]:
idx_flat.set_index(['행정구역','년도'])

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [120]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    1
1    3
2    7
3    8
4    0
dtype: int64

In [123]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                                    columns=['A','B','C'])
df

   A  B  C
0  4  8  3
1  5  8  2
2  7  9  2

In [124]:
np.exp(s)

0       2.718282
1      20.085537
2    1096.633158
3    2980.957987
4       1.000000
dtype: float64

In [126]:
np.cos(df * np.pi/4)

          A         B             C
0 -1.000000  1.000000 -7.071068e-01
1 -0.707107  1.000000  6.123234e-17
2  0.707107  0.707107  6.123234e-17

In [127]:
s1 = pd.Series([1,3,5,7,9], index=[0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10], index=[1,2,3,4,5])
s1 + s2 # index가 기준이기 때문에 index가 같은 것끼리 연산이 됌.

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [128]:
s1.add(s2, fill_value=0) # 각 시리즈 데이터의 없는 값은 fill_value=0으로 채워서 계산해줌

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [130]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3,3)),
                   columns=list('ACD'))
df1

    A  C   D
0  19  9   4
1   3  0  19
2  16  9   9

In [131]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5,5)),
                   columns=list('BAECD'))
df2

    B   A   E   C   D
0   1  16  12  12   2
1   4   4   4  15   6
2   5  14   9  11  18
3   4   0  16   9   8
4  11   1   8   9  13

In [132]:
df1 + df2

      A   B     C     D   E
0  35.0 NaN  21.0   6.0 NaN
1   7.0 NaN  15.0  25.0 NaN
2  30.0 NaN  20.0  27.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [133]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

           A          B          C          D          E
0  35.000000  10.777778  21.000000   6.000000  21.777778
1   7.000000  13.777778  15.000000  25.000000  13.777778
2  30.000000  14.777778  20.000000  27.000000  18.777778
3   9.777778  13.777778  18.777778  17.777778  25.777778
4  10.777778  20.777778  18.777778  22.777778  17.777778

### 연산자 범용 함수

#### add()

In [134]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[7, 2, 9],
       [1, 2, 6],
       [9, 9, 7]])

In [135]:
a + a[0]

array([[14,  4, 18],
       [ 8,  4, 15],
       [16, 11, 16]])

In [138]:
df = pd.DataFrame(a, columns=list('ABC'))
df

   A  B  C
0  7  2  9
1  1  2  6
2  9  9  7

In [139]:
df + df.iloc[0]

    A   B   C
0  14   4  18
1   8   4  15
2  16  11  16

In [140]:
df.add(df.iloc[0])

    A   B   C
0  14   4  18
1   8   4  15
2  16  11  16

#### sub() / subtract()

In [141]:
a

array([[7, 2, 9],
       [1, 2, 6],
       [9, 9, 7]])

In [142]:
a - a[0]

array([[ 0,  0,  0],
       [-6,  0, -3],
       [ 2,  7, -2]])

In [143]:
df

   A  B  C
0  7  2  9
1  1  2  6
2  9  9  7

In [144]:
df - df.iloc[0]

   A  B  C
0  0  0  0
1 -6  0 -3
2  2  7 -2

In [145]:
df.sub(df.iloc[0])

   A  B  C
0  0  0  0
1 -6  0 -3
2  2  7 -2

In [147]:
df.subtract(df['B'], axis=0)

   A  B  C
0  5  0  7
1 -1  0  4
2  0  0 -2

#### mul() / multply()

In [149]:
a

array([[7, 2, 9],
       [1, 2, 6],
       [9, 9, 7]])

In [153]:
a * a[1]

array([[ 7,  4, 54],
       [ 1,  4, 36],
       [ 9, 18, 42]])

In [151]:
df

   A  B  C
0  7  2  9
1  1  2  6
2  9  9  7

In [152]:
df * df.iloc[1]

   A   B   C
0  7   4  54
1  1   4  36
2  9  18  42

In [154]:
df.mul(df.iloc[1])

   A   B   C
0  7   4  54
1  1   4  36
2  9  18  42

In [155]:
df.multiply(df.iloc[2])

    A   B   C
0  63  18  63
1   9  18  42
2  81  81  49

#### truediv() /  div() / divide() / floordiv()

In [156]:
a

array([[7, 2, 9],
       [1, 2, 6],
       [9, 9, 7]])

In [157]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.14285714, 1.        , 0.66666667],
       [1.28571429, 4.5       , 0.77777778]])

In [158]:
df

   A  B  C
0  7  2  9
1  1  2  6
2  9  9  7

In [159]:
df / df.iloc[0]

          A    B         C
0  1.000000  1.0  1.000000
1  0.142857  1.0  0.666667
2  1.285714  4.5  0.777778

In [160]:
df.truediv(df.iloc[0])

          A    B         C
0  1.000000  1.0  1.000000
1  0.142857  1.0  0.666667
2  1.285714  4.5  0.777778

In [161]:
df.div(df.iloc[1])

     A    B         C
0  7.0  1.0  1.500000
1  1.0  1.0  1.000000
2  9.0  4.5  1.166667

In [162]:
df.divide(df.iloc[2])

          A         B         C
0  0.777778  0.222222  1.285714
1  0.111111  0.222222  0.857143
2  1.000000  1.000000  1.000000

In [163]:
a // a[0]

array([[1, 1, 1],
       [0, 1, 0],
       [1, 4, 0]])

In [164]:
df.floordiv(df.iloc[0])

   A  B  C
0  1  1  1
1  0  1  0
2  1  4  0

#### mod()

In [165]:
a

array([[7, 2, 9],
       [1, 2, 6],
       [9, 9, 7]])

In [166]:
a % a[0]

array([[0, 0, 0],
       [1, 0, 6],
       [2, 1, 7]])

In [167]:
df

   A  B  C
0  7  2  9
1  1  2  6
2  9  9  7

In [168]:
df.mod(df.iloc[0])

   A  B  C
0  0  0  0
1  1  0  6
2  2  1  7

#### pow()

In [169]:
a

array([[7, 2, 9],
       [1, 2, 6],
       [9, 9, 7]])

In [170]:
a ** a[0]

array([[   823543,         4, 387420489],
       [        1,         4,  10077696],
       [  4782969,        81,  40353607]])

In [171]:
df

   A  B  C
0  7  2  9
1  1  2  6
2  9  9  7

In [172]:
df.pow(df.iloc[0])

         A   B          C
0   823543   4  387420489
1        1   4   10077696
2  4782969  81   40353607

In [173]:
row = df.iloc[0, ::2]
row

A    7
C    9
Name: 0, dtype: int64

In [174]:
df - row

     A   B    C
0  0.0 NaN  0.0
1 -6.0 NaN -3.0
2  2.0 NaN -2.0

### 정렬(Sort)

In [176]:
s = pd.Series(range(5), index=['A','D','B','C','E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [177]:
s.sort_index() # index 기준으로 정렬

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [178]:
s.sort_values() # value 기준으로 정렬

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [180]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index= [2, 4, 1, 3],
                  columns=list('BACD'))
df

   B  A  C  D
2  6  1  0  7
4  6  5  8  3
1  6  8  5  6
3  1  8  5  7

In [182]:
df.sort_index()

   B  A  C  D
1  6  8  5  6
2  6  1  0  7
3  1  8  5  7
4  6  5  8  3

In [186]:
df.sort_index(axis=1)

   A  B  C  D
2  1  6  0  7
4  5  6  8  3
1  8  6  5  6
3  8  1  5  7

In [184]:
df.sort_values(by='A')

   B  A  C  D
2  6  1  0  7
4  6  5  8  3
1  6  8  5  6
3  1  8  5  7

In [185]:
df.sort_values(by=['A','C'])

   B  A  C  D
2  6  1  0  7
4  6  5  8  3
1  6  8  5  6
3  1  8  5  7

### 순위(Ranking)

In [187]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4 ,2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [188]:
s.rank() # 0번째 값이 2위, 1번째 값이 6위...

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [189]:
s.rank(method='first') # 동일한 값이 있으면 먼저 온 것의 순위를 높여준다

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [190]:
s.rank(method='max') # 같은 값을 가지는 그룹을 높은 순위로 지정

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

In [191]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [192]:
%timeit df1  + df2 + df3 + df4 # 데이터프레임을 다 더하는데 걸리는 시간 측정

10 loops, best of 5: 56.7 ms per loop

In [193]:
%timeit pd.eval('df1 + df2 + df3 + df4') # ?

10 loops, best of 5: 39.5 ms per loop

In [194]:
%timeit df1 + -df2 / (-df3 * df4)

10 loops, best of 5: 90 ms per loop

In [195]:
%timeit pd.eval('df1 + -df2 / (-df3 * df4)')

10 loops, best of 5: 47.1 ms per loop

In [198]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

10 loops, best of 5: 54.3 ms per loop

In [199]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

10 loops, best of 5: 83.3 ms per loop

In [201]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A','B','C','D','E'])
df.head()

          A         B         C         D         E
0  0.123363  0.210270  0.718736  0.021294  0.172657
1  0.061798  0.987190  0.798482  0.760946  0.195095
2  0.587355  0.389459  0.900836  0.052658  0.453730
3  0.913433  0.076508  0.350143  0.412415  0.731766
4  0.850226  0.624686  0.101242  0.944226  0.336811

In [202]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

100 loops, best of 5: 12.3 ms per loop

In [203]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

100 loops, best of 5: 7.01 ms per loop

In [204]:
%timeit df.eval('A + B / C - D * E')

100 loops, best of 5: 11.1 ms per loop

In [205]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

          A         B         C         D         E         R
0  0.123363  0.210270  0.718736  0.021294  0.172657  0.412242
1  0.061798  0.987190  0.798482  0.760946  0.195095  1.149674
2  0.587355  0.389459  0.900836  0.052658  0.453730  0.995793
3  0.913433  0.076508  0.350143  0.412415  0.731766  0.830145
4  0.850226  0.624686  0.101242  0.944226  0.336811  6.702437

In [206]:
df.eval('R = A - B / C + D * E', inplace=True)
df.head()

          A         B         C         D         E         R
0  0.123363  0.210270  0.718736  0.021294  0.172657 -0.165515
1  0.061798  0.987190  0.798482  0.760946  0.195095 -1.026078
2  0.587355  0.389459  0.900836  0.052658  0.453730  0.178918
3  0.913433  0.076508  0.350143  0.412415  0.731766  0.996720
4  0.850226  0.624686  0.101242  0.944226  0.336811 -5.001986

In [208]:
col_mean = df.mean(1)
df['A'] + col_mean

0         0.303498
1         0.358037
2         1.014515
3         1.493597
4         0.492760
            ...
999995   -0.071036
999996    0.455837
999997    0.968056
999998    1.437753
999999    1.452320
Length: 1000000, dtype: float64

In [209]:
df.eval('A + @col_mean')

0         0.303498
1         0.358037
2         1.014515
3         1.493597
4         0.492760
            ...
999995   -0.071036
999996    0.455837
999997    0.968056
999998    1.437753
999999    1.452320
Length: 1000000, dtype: float64

In [210]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C >0.5)]

               A         B         C         D         E         R
0       0.123363  0.210270  0.718736  0.021294  0.172657 -0.165515
5       0.304360  0.312059  0.884780  0.919896  0.297831  0.225637
8       0.372067  0.299256  0.974955  0.450200  0.342030  0.219105
51      0.286960  0.299462  0.802894  0.945370  0.309023  0.206123
53      0.448798  0.090392  0.987508  0.890224  0.770473  1.043156
...          ...       ...       ...       ...       ...       ...
999954  0.190272  0.277519  0.508228  0.228610  0.430192 -0.257435
999955  0.253289  0.084830  0.694662  0.604914  0.321431  0.325610
999984  0.355890  0.382027  0.912829  0.234883  0.006932 -0.060990
999993  0.175226  0.261650  0.928567  0.908990  0.366648  0.226728
999997  0.386210  0.390044  0.922995  0.704904  0.658863  0.428059

[125303 rows x 6 columns]

In [212]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C >0.5)]')

               A         B         C         D         E         R
0       0.123363  0.210270  0.718736  0.021294  0.172657 -0.165515
5       0.304360  0.312059  0.884780  0.919896  0.297831  0.225637
8       0.372067  0.299256  0.974955  0.450200  0.342030  0.219105
51      0.286960  0.299462  0.802894  0.945370  0.309023  0.206123
53      0.448798  0.090392  0.987508  0.890224  0.770473  1.043156
...          ...       ...       ...       ...       ...       ...
999954  0.190272  0.277519  0.508228  0.228610  0.430192 -0.257435
999955  0.253289  0.084830  0.694662  0.604914  0.321431  0.325610
999984  0.355890  0.382027  0.912829  0.234883  0.006932 -0.060990
999993  0.175226  0.261650  0.928567  0.908990  0.366648  0.226728
999997  0.386210  0.390044  0.922995  0.704904  0.658863  0.428059

[125303 rows x 6 columns]

In [216]:
df.query('(A < 0.5) and (B < 0.5) and (C >0.5)')

               A         B         C         D         E         R
0       0.123363  0.210270  0.718736  0.021294  0.172657 -0.165515
5       0.304360  0.312059  0.884780  0.919896  0.297831  0.225637
8       0.372067  0.299256  0.974955  0.450200  0.342030  0.219105
51      0.286960  0.299462  0.802894  0.945370  0.309023  0.206123
53      0.448798  0.090392  0.987508  0.890224  0.770473  1.043156
...          ...       ...       ...       ...       ...       ...
999954  0.190272  0.277519  0.508228  0.228610  0.430192 -0.257435
999955  0.253289  0.084830  0.694662  0.604914  0.321431  0.325610
999984  0.355890  0.382027  0.912829  0.234883  0.006932 -0.060990
999993  0.175226  0.261650  0.928567  0.908990  0.366648  0.226728
999997  0.386210  0.390044  0.922995  0.704904  0.658863  0.428059

[125303 rows x 6 columns]

In [217]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

               A         B         C         D         E         R
0       0.123363  0.210270  0.718736  0.021294  0.172657 -0.165515
5       0.304360  0.312059  0.884780  0.919896  0.297831  0.225637
8       0.372067  0.299256  0.974955  0.450200  0.342030  0.219105
12      0.384327  0.156976  0.242181  0.685896  0.819364  0.298150
13      0.289154  0.270918  0.292959  0.138423  0.776496 -0.528126
...          ...       ...       ...       ...       ...       ...
999979  0.494362  0.420463  0.255665  0.113021  0.259602 -1.120885
999983  0.217887  0.335639  0.424567  0.714536  0.647096 -0.110283
999984  0.355890  0.382027  0.912829  0.234883  0.006932 -0.060990
999993  0.175226  0.261650  0.928567  0.908990  0.366648  0.226728
999997  0.386210  0.390044  0.922995  0.704904  0.658863  0.428059

[250357 rows x 6 columns]

In [220]:
df.query('A < @col_mean and B < @col_mean')

               A         B         C         D         E         R
0       0.123363  0.210270  0.718736  0.021294  0.172657 -0.165515
5       0.304360  0.312059  0.884780  0.919896  0.297831  0.225637
8       0.372067  0.299256  0.974955  0.450200  0.342030  0.219105
12      0.384327  0.156976  0.242181  0.685896  0.819364  0.298150
13      0.289154  0.270918  0.292959  0.138423  0.776496 -0.528126
...          ...       ...       ...       ...       ...       ...
999979  0.494362  0.420463  0.255665  0.113021  0.259602 -1.120885
999983  0.217887  0.335639  0.424567  0.714536  0.647096 -0.110283
999984  0.355890  0.382027  0.912829  0.234883  0.006932 -0.060990
999993  0.175226  0.261650  0.928567  0.908990  0.366648  0.226728
999997  0.386210  0.390044  0.922995  0.704904  0.658863  0.428059

[250357 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)

### GroupBy 연산

### 피벗 테이블(Pivot Table)

### 범주형(Categorical) 데이터

## 문자열 연산

#### 문자열 연산자

#### 기타 연산자

#### 정규표현식

## 시계열 처리

#### 시계열 데이터 구조

### 시계열 기본

### 주기와 오프셋

### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장

### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리

### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly